aaron-wortham:
  name: Aaron Wortham
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Aaron%20Wortham.jpg

glen-egbert:
  name: Glen Egbert
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Glen%20Egbert.jpg

ian-anderson:
  name: Ian Anderson
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Ian%20Anderson.jpg

jim-sutton:
  name: Jim Sutton
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Jim%20Sutton.jpg

kavita-sachdeva:
  name: Kavita Sachdeva
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Kavita%20Sachdeva.jpg

luke-aiken:
  name: Luke Aiken
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Luke%20Aiken.jpg

rolando-navarette:
  name: Rolando Navarette
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Rolando%20Navarette.jpg

sara-simon:
  name: Sara Simon
  cohort: 1407
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1407/Sara%20Simon.jpg

orion-osborn:
  name: Orion Osborn
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Orion%20Osborn.jpg

rich-shea:
  name: Rich Shea
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Rich%20Shea.jpg

alex-robinson:
  name: Alex Robinson
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Alex%20Robinson.jpg

andrew-overby:
  name: Andrew Overby
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Andrew%20Overby.jpg

bhargavi-satpathy:
  name: Bhargavi Satpathy
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Bhargavi%20Satpathy.jpg

brandon-mrsny:
  name: Brandon Mrsny
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Brandon%20Mrsny.jpg

bryce-holcomb:
  name: Bryce Holcomb
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Bryce%20Holcomb.jpg

chris-luhring:
  name: Chris Luhring
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Chris%20Luhring.jpg

dustin-gault:
  name: Dustin Gault
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Dustin%20Gault.jpg

edward-mcCarthy:
  name: Edward McCarthy
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Edward%20McCarthy.jpg

emily-berkeley:
  name: Emily Berkeley
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Emily%20Berkeley.jpg

jeff-wan:
  name: Jeff Wan
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Jeff%20Wan.jpg

juan-navarro:
  name: Juan Navarro
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Juan%20Navarro.jpg

kalah-cheek:
  name: Kalah Cheek
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Kalah%20Cheek.jpg

kit-pearson:
  name: Kit Pearson
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Kit%20Pearson.jpg

krista-nelson:
  name: Krista Nelson
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Krista%20Nelson.jpg

laura-whalin:
  name: Laura Whalin
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Laura%20Whalin.jpg

lori-culberson:
  name: Lori Culberson
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Lori%20Culberson.jpg

lydia-shafer:
  name: Lydia Shafer
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Lydia%20Shafer.jpg

mike-dao:
  name: Mike Dao
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Mike%20Dao.jpg

nathan-owsiany:
  name: Nathan Owsiany
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Nathan%20Owsiany.jpg

scott-crawford:
  name: Scott Crawford
  cohort: 1410
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1410/Scott%20Crawford.jpg

adam-smith:
  name: Adam Smith
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Adam%20Smith.jpg
  cohort: 1409

alex-jensen:
  name: Alex Jensen
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Alex%20Jensen.jpg
  cohort: 1409

chandra-carney:
  name: Chandra Carney
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Chandra%20Carney.jpg
  cohort: 1409

christopher-bynum:
  name: Christopher Bynum
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Christopher%20Bynum.jpg
  cohort: 1409

danny-glunz:
  name: Danny Glunz
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Danny%20Glunz.jpg
  cohort: 1409

david-bayendor:
  name: David Bayendor
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/David%20Bayendor.jpg
  cohort: 1409

greg-narajka:
  name: Greg Narajka
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Greg%20Narajka.jpg
  cohort: 1409

herbert-joseph:
  name: Herbert Joseph
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Herbert%20Joseph.jpg
  cohort: 1409

kalah-cheek:
  name: Kalah Cheek
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Kalah%20Cheek.jpg
  cohort: 1409

konr-laron:
  name: Konr Laron
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Konr%20Laron.jpg
  cohort: 1409

sam-kulmann:
  name: Sam Kulmann
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Sam%20Kulmann.jpg
  cohort: 1409

timothy-mee:
  name: Timothy Mee
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Timothy%20Mee.jpg
  cohort: 1409

travis-yoder:
  name: Travis Yoder
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Travis%20Yoder.jpg
  cohort: 1409

viki-harrod:
  name: Viki Harrod
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Viki%20Harrod.jpg
  cohort: 1409

zach-routhier:
  name: Zach Routhier
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Zach%20Routhier.jpg
  cohort: 1409

chase-van-hekken:
  name: Chase van Hekken
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1409/Chase%20van%20Hekken.jpg
  cohort: 1409

andrew-overby:
  name: Andrew Overby
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Andrew%20Overby.jpg
  cohort: 1412

austin-wood:
  name: Austin Wood
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Austin%20Wood.jpg
  cohort: 1412

DJ-greenfield:
  name: DJ Greenfield
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/DJ%20Greenfield.jpg
  cohort: 1412

david-maurer:
  name: David Maurer
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/David%20Maurer.jpg
  cohort: 1412

edward-macarthy:
  name: Edward Macarthy
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Edward%20Macarthy.jpg
  cohort: 1412

fred-block:
  name: Fred Block
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Fred%20Block.jpg
  cohort: 1412

jack-yeh:
  name: Jack Yeh
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Jack%20Yeh.jpg
  cohort: 1412

jeffrey-gu:
  name: Jeffrey Gu
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Jeffrey%20Gu.jpg
  cohort: 1412

kyle-hensen:
  name: Kyle Hensen
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Kyle%20Hensen.jpg
  cohort: 1412

kyra-weber:
  name: Kyra Weber
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Kyra%20Weber.jpg
  cohort: 1412

lori-culberson:
  name: Lori Culberson
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Lori%20Culberson.jpg
  cohort: 1412

manny-navarro:
  name: Manny Navarro
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Manny%20Navarro.jpg
  cohort: 1412

markus-olsen:
  name: Markus Olsen
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Markus%20Olsen.jpg
  cohort: 1412

miriam-moser:
  name: Miriam Moser
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Miriam%20Moser.jpg
  cohort: 1412

paul-grever:
  name: Paul Grever
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Paul%20Grever.jpg
  cohort: 1412

stanley-siudzinski:
  name: Stanley Siudzinski
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Stanley%20Siudzinski.jpg
  cohort: 1412

teresa-finn:
  name: Teresa Finn
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Teresa%20Finn.jpg
  cohort: 1412

tino-espinoza:
  name: Tino Espinoza
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Tino%20Espinoza.jpg
  cohort: 1412

trey-tomlinson:
  name: Trey Tomlinson
  image_url: http://turing-headshots.s3-us-west-1.amazonaws.com/turing-1412/Trey%20Tomlinson.jpg
  cohort: 1412
